frase='Curso em Video Python'
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[1:15])
print(frase[1::2])
print(frase.count('o'))
print(len(frase))
print('-'.join(frase))
print(frase.replace('Video','Aula'))
print('Curso' in frase)
print(frase.find('Python'))
print(frase.find('python'))
print(frase.lower().find('python'))
print(frase.split())